---
- name: ENABLE UFW
  ufw:
    state: enabled
    policy: allow

- name: CONFIGURE UFW UDP PORTS
  ufw:
    rule: allow
    proto: udp
    port: "{{ item }}"
  with_items:
    - 30303

- name: CONFIGURE UFW TCP PORTS
  ufw:
    rule: allow
    proto: tcp
    port: "{{ item }}"
  with_items:
    - 30303
    - 22

- name: ENABLE UFW
  ufw:
    state: enabled
    policy: deny
